### ISSUE TITLE
OpenVAS on HTTPS 

### ISSUE THREAD

**Issue by andreicenja** [mattias-ohlsson/docker-openvas#1]
Hi,
I was wondering why the code is set to make OpenVAS only listen to http. 
I'd like to use your container, and https seems to work by disabling http-only and GSAD_PORT - and explicitly specifying the locations for the certs to /etc/pki/... 
Which leads me to believe you might have had stronger reasons for only enabling http.
Thanks!
Best regards,
Andrei

**Comment by mattias-ohlsson** [comment]
Hi! My primary goal was to get a working image without third party packages (only Fedora packages) and it only listens locally (localhost).

Perhaps you can use port mapping with SSH if you run the image on another computer / server? Certificate management adds too much complexity in terms of how simple the image is otherwise.

**Comment by andreicenja** [comment]
Hi! Thank you for your reply! 

I've also discovered other tiny things that were required in our case, so I ended up creating a fork.

Thank you for creating this container, I'm more comfortable using RHEL/CentOS/Fedora ;-)

Best regards,
Andrei
